global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: consumer0
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    metrics_path: /metrics
    static_configs:
    # consumer0
    - targets: ['consumer0.app.domain:80']
      labels:
        role: 'consumer0'
    - targets: ['consumer0.app.domain:81']
      labels:
        role: 'consumer1'
    - targets: ['consumer0.app.domain:82']
      labels:
        role: 'consumer2'
    - targets: ['consumer0.app.domain:83']
      labels:
        role: 'consumer3'
    - targets: ['consumer0.app.domain:84']
      labels:
        role: 'consumer4'
    - targets: ['consumer0.app.domain:85']
      labels:
        role: 'consumer5'
    - targets: ['consumer0.app.domain:86']
      labels:
        role: 'consumer6'
    - targets: ['consumer0.app.domain:87']
      labels:
        role: 'consumer7'
    - targets: ['consumer0.app.domain:88']
      labels:
        role: 'consumer8'
    - targets: ['consumer0.app.domain:89']
      labels:
        role: 'consumer9'
    # consumer1
    - targets: ['consumer1.app.domain:80']
      labels:
        role: 'consumer0'
    - targets: ['consumer1.app.domain:81']
      labels:
        role: 'consumer1'
    - targets: ['consumer1.app.domain:82']
      labels:
        role: 'consumer2'
    - targets: ['consumer1.app.domain:83']
      labels:
        role: 'consumer3'
    - targets: ['consumer1.app.domain:84']
      labels:
        role: 'consumer4'
    - targets: ['consumer1.app.domain:85']
      labels:
        role: 'consumer5'
    - targets: ['consumer1.app.domain:86']
      labels:
        role: 'consumer6'
    - targets: ['consumer1.app.domain:87']
      labels:
        role: 'consumer7'
    - targets: ['consumer1.app.domain:88']
      labels:
        role: 'consumer8'
    - targets: ['consumer1.app.domain:89']
      labels:
        role: 'consumer9'
    # consumer2
    - targets: ['consumer2.app.domain:80']
      labels:
        role: 'consumer0'
    - targets: ['consumer2.app.domain:81']
      labels:
        role: 'consumer1'
    - targets: ['consumer2.app.domain:82']
      labels:
        role: 'consumer2'
    - targets: ['consumer2.app.domain:83']
      labels:
        role: 'consumer3'
    - targets: ['consumer2.app.domain:84']
      labels:
        role: 'consumer4'
    - targets: ['consumer2.app.domain:85']
      labels:
        role: 'consumer5'
    - targets: ['consumer2.app.domain:86']
      labels:
        role: 'consumer6'
    - targets: ['consumer2.app.domain:87']
      labels:
        role: 'consumer7'
    - targets: ['consumer2.app.domain:88']
      labels:
        role: 'consumer8'
    - targets: ['consumer2.app.domain:89']
      labels:
        role: 'consumer9'
    # consumer3
    - targets: ['consumer3.app.domain:80']
      labels:
        role: 'consumer0'
    - targets: ['consumer3.app.domain:81']
      labels:
        role: 'consumer1'
    - targets: ['consumer3.app.domain:82']
      labels:
        role: 'consumer2'
    - targets: ['consumer3.app.domain:83']
      labels:
        role: 'consumer3'
    - targets: ['consumer3.app.domain:84']
      labels:
        role: 'consumer4'
    - targets: ['consumer3.app.domain:85']
      labels:
        role: 'consumer5'
    - targets: ['consumer3.app.domain:86']
      labels:
        role: 'consumer6'
    - targets: ['consumer3.app.domain:87']
      labels:
        role: 'consumer7'
    - targets: ['consumer3.app.domain:88']
      labels:
        role: 'consumer8'
    - targets: ['consumer3.app.domain:89']
      labels:
        role: 'consumer9'
  - job_name: producer
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    metrics_path: /metrics
    static_configs:
    - targets: ['producer.app.domain:80']
      labels:
        role: 'producer'

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
