---
- name: "AWS - Run application"
  hosts: "all"
  become: yes
  gather_facts: true
  roles:
  - { role: roles/docker, tags: docker}
  - { role: roles/docker-auth, tags: docker }
  - { role: roles/docker-containers, tags: containers }
