---
- name: Log into private registry and force re-authorization
  docker_login:
    registry_url: "{{ item.url | default('https://index.docker.io/v1/') }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    reauthorize: true
  with_items: "{{ docker_auth }}"
